---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Analysis of scRNA and bulk RNA sequencing data for "Characterizing gene expression responses to biomechanical strain in an in vitro model of osteoarthritis" project.

LCL-derived iPSCs from 3 Yoruba individuals were differentiated into mesenchymal stem cells and subsequently into chondrocytes. iPSC-derived chondrocytes were either placed under control conditions or treated with cyclic tensile strain for 24 hours (Total of 6 individual x treatment pairs). 3 technical replicates of the MSC-chondrocyte differentiation + strain/control treatment were conducted.Single cell RNAseq using the 10x platform was conducted for one replicate of the experiment (collection of one sample failed, meaning only 5 samples were single-cell sequenced). Bulk RNA sequencing was conducted for all 3 technical replicates.

If you are running the files in this repository to recreate the analyses, running them in the order they appear on this list is recommended.

## Single-cell data

* [Pre-processing of raw 10x files into count matrices and demultiplexing](preProcess_scRNA.html)

    + Figure S3
    
* [Integration and clustering of scRNA sequencing data](clustering_scRNA.html)

    + Figures 2B, 2C, 2D

* [Aggregation of external scRNA-seq data for topic model](external_scRNA.html)

* [Fitting and interpreting topic model with external data](topicModel_scRNA.html)

    + Figure 2A, S4, S5

## Bulk Data

* [Pre-processing of raw bulk RNA sequencing files](preProcess_bulkRNA.html)

* [Download Gene Annotations for GO analysis](download_gene_annotation.html)

* [Normalization and filtering of bulkRNAseq data](normFilter_bulkRNA.html)

    + Figure S10

* [Modeling and removing unwanted technical variation](removeUnwantedVariation_bulkRNA.html)

    + Figures 3A, 3B, S6, S8, S9

* [Differential expression using limma/voom](DEanalysis_bulkRNA.html)

    + Figure 4

* [Variance partitioning the bulk RNAseq data](variation_bulkRNA.html)

    + Figures 3C, S7

* [Selected examples of inter-individual heterogeneity](heterogeneity_bulkRNA.html)

    + Figure 5

## Power Analysis

* [Conducting power analysis for eQTL mapping](powerAnalysis.html)

    + Figure 6
