---
title: "Fitting a topic model k = 7 to iPSC-chondrocytes and external data"
author: "Anthony Hung"
date: "2021-01-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction

This code will load in the combined scRNA seq data from external datasets combined with the iPSC-chondrocytes from the current study and fit a topic model (k=7) to the data. It then interprets the topics.

```{r load data and packages}
library(fastTopics)
library(Seurat)
library(Matrix)

#load data (stored in a seurat object)
merged_data <- readRDS("data/external_scRNA/merged_external_scRNA.rds")

#Extract raw count matrix from seurat object and get it in correct format for fastTopics
#need to fit the model to the count data (unintegrated)
raw_counts_allGenes <- Combined.common.allGenes@assays$RNA@counts
raw_counts_allGenes <- as.matrix(raw_counts_allGenes)
#remove genes without any counts in droplets
raw_counts_allGenes <- raw_counts_allGenes[rowSums(raw_counts_allGenes > 0) > 0,] 
#get into correct orientation (barcodes x features)
raw_counts_allGenes <- Matrix(raw_counts_allGenes, sparse = TRUE)
raw_counts_allGenes <- t(raw_counts_allGenes)
dim(raw_counts_allGenes)
```

# Use fastTopics functions to fit a topic model k=7 to the data

```{r fit topic model}
fit <- fit_poisson_nmf(raw_counts_allGenes,k = 7,numiter = 100)
saveRDS(fit, "output/fasttopics/Combined_external_data_allGenes_k=7.rds")

fit <- readRDS("output/fasttopics/Combined_external_data_allGenes_k=7.rds")

#compute weights and topics (need to add up to 1)
l <- fit$L
f <- fit$F
weights <- sweep(l, MARGIN = 2, colSums(f), `*`)
scale <- rowSums(weights)
weights <- weights / scale
topics <- f / colSums(f) # add up to 1
```


```{r plot correlations external}
library(stringr)
library(pheatmap)
library(dummies)
library(tidyverse)
#plot heatmap of topic weights for samples
#get labels of cells and reorder to group them
sample <- as.data.frame(Combined.common@meta.data$Cell.Type)
sample_labels <- sample %>% 
     dplyr::transmute(Cell.Type = stringr::word(`Combined.common@meta.data$Cell.Type`, start = 1))
rownames(sample_labels) <- rownames(Combined.common@meta.data)
sample <- sample_labels %>% 
     dplyr::arrange(Cell.Type)
#reorder weights df to match sample order
weights_reordered <- weights[match(rownames(sample), rownames(weights)),]
#make the plot (color strip on the left is by indivdual)
pheatmap(weights_reordered, cluster_cols = FALSE, cluster_rows = FALSE, annotation_row = sample,
         show_rownames = FALSE, main = "Heatmap of topic weights grouped by cell labels")
#same heatmap but group all the cells that are of the same label together (more interpretable??)
sample_dummy <- as.data.frame(Combined.common@meta.data$Cell.Type)
sample_dummy <- sample_dummy %>% 
     dplyr::transmute(Cell.Type = stringr::word(`Combined.common@meta.data$Cell.Type`, start = 1))
rownames(sample_dummy) <- rownames(Combined.common@meta.data)
sample_dummies <- dummy.data.frame(sample_dummy)
cor_by_sample <- cor(sample_dummies, weights, method = "pearson")
pheatmap(cor_by_sample, cluster_cols = TRUE, cluster_rows = TRUE, main = "Correlation by sample label")

#same heatmap but group all the cells that are of the same label and strain condition together
sample_dummy <- as.data.frame(Combined.common@meta.data$Cell.Type)
sample_dummy$`Combined.common@meta.data$Cell.Type` <- as.character(sample_dummy$`Combined.common@meta.data$Cell.Type`)
rownames(sample_dummy) <- rownames(Combined.common@meta.data)
metadata <- as.data.frame(Combined.common@meta.data)
metadata <- metadata %>% filter(orig.ident == "ANT1" | orig.ident == "ANT2")
sample_dummy$`Combined.common@meta.data$Cell.Type`[match(rownames(metadata), rownames(sample_dummy))] <- metadata$labels
sample_dummy$`Combined.common@meta.data$Cell.Type` <- gsub("NA18855_Strain|NA19160_Strain", "iPSC-Chondrocyte_Strain", sample_dummy$`Combined.common@meta.data$Cell.Type`)
sample_dummy$`Combined.common@meta.data$Cell.Type` <- gsub("NA18855_Unstrain|NA19160_Unstrain|NA18856_Unstrain", "iPSC-Chondrocyte_Control", sample_dummy$`Combined.common@meta.data$Cell.Type`)
sample_dummy <- sample_dummy %>% 
     dplyr::transmute(Cell.Type = stringr::word(`Combined.common@meta.data$Cell.Type`, start = 1))
rownames(sample_dummy) <- rownames(Combined.common@meta.data)
sample_dummies <- dummy.data.frame(sample_dummy)
cor_by_sample <- cor(sample_dummies, weights, method = "pearson")
cor_by_sample
pheatmap(cor_by_sample, cluster_cols = TRUE, cluster_rows = TRUE, main = "Correlation by sample label")

MSC_markers <- c("THY1", "NT5E", "ENG")
Chondrocyte_markers <- c("COL2A1", "ACAN", "SOX9", "SOX5", "SOX6", "COL9A1")
Hepatocyte_markers <- c("ALB")
iPSC_markers <- c("POU5F1", "SOX2", "NANOG")
markers <- c(iPSC_markers, Hepatocyte_markers, Chondrocyte_markers, MSC_markers)

markers_description <- data.frame(marker_type = c(rep("iPSC", 3), rep("Hepatocyte", 1), rep("Chondrocyte", 6), rep("MSC", 3)))
rownames(markers_description) <- markers

#plot heatmap of relative expression of marker genes in each topic
topics_markers <- topics[markers,]
pheatmap(topics_markers, cluster_cols = FALSE, cluster_rows = FALSE, annotation_row = markers_description, scale = "row")
topics_markers <- topics[markers[-4],]
pheatmap(topics_markers, cluster_cols = FALSE, cluster_rows = FALSE, annotation_row = markers_description)
```

Look at structure plot

```{r structure plot external}
set.seed(1)
topic_colors <- c("grey", "firebrick","turquoise","gold","royalblue", "salmon", "forestgreen", "black",
                  "orangered")
topics_order <- c(1, 2, 4, 6, 3, 5, 7)
rows_keep <- sort(c(sample(which(sample_labels$Cell.Type == "Hepatocyte"), 800),
               sample(which(sample_labels$Cell.Type == "iPSC"), 800),
               sample(which(sample_labels$Cell.Type == "iPSC-MSC"), 800),
               which(sample_labels$Cell.Type == "iPSC-Chondrocyte"),
               sample(which(sample_labels$Cell.Type == "iPSC-Chondro_GAH"), 800),
               sample(which(sample_labels$Cell.Type == "iPSC-Osteo"), 800),
               #which(sample_labels$Cell.Type == "Chondrogenic"),
               sample(which(sample_labels$Cell.Type == "dicks_d7"), 800),
               sample(which(sample_labels$Cell.Type == "dicks_d14"), 800),
               sample(which(sample_labels$Cell.Type == "dicks_d28"), 800),
               sample(which(sample_labels$Cell.Type == "dicks_d42"), 800),
               sample(which(sample_labels$Cell.Type == "Chondrocyte_"), 800),
               sample(which(sample_labels$Cell.Type == "Chondro"), 800)))
structure_plot <- structure_plot(select(poisson2multinom(fit),loadings = rows_keep),
                      grouping = factor(sample_labels[rows_keep,"Cell.Type"], 
                                        c("Hepatocyte", "iPSC", "iPSC-MSC", "iPSC-Osteo", 
                                          "iPSC-Chondro_GAH", "iPSC-Chondrocyte", "dicks_d7", "dicks_d14", "dicks_d28", "dicks_d42", "Chondrocyte_", "Chondro")),
                      topics = topics_order,
                      colors = topic_colors[topics_order],
                      perplexity = c(50),
                      n = 6043,gap = 100,num_threads = 4,verbose = FALSE)
print(structure_plot)
```

# Differential Expression analysis

```{r DE}
diff_count_topics <- diff_count_analysis(fit, raw_counts_allGenes)

#all seem to be in chondro
fit_chondro <- merge_topics(poisson2multinom(fit), c("k7", "k6", "k5", "k3"))
diff_count_chondro <- diff_count_analysis(fit_chondro, raw_counts_allGenes)
```

```{r volcanoplot function}
library(ggrepel)
library(cowplot)
volcano_plot_with_highlighted_genes <- function (diff_count_res, k, 
                                                 genes, ...) {
  dat <- data.frame(beta  = diff_count_res$beta[genes,k],
                    y     = abs(diff_count_res$Z[genes,k]),
                    label = genes) 
  rows <- match(genes,rownames(diff_count_res$beta))
  rownames(diff_count_res$beta)[rows] <- ""
  rownames(diff_count_res$Z)[rows] <- ""
  return(volcano_plot(diff_count_res,k = k,
                      ggplot_call = volcano_plot_ggplot_call,...) +
         geom_text_repel(data = dat,
                         mapping = aes(x = beta,y = y,label = label),
                         inherit.aes = FALSE,color = "black",size = 5,
                         fontface = "italic",segment.color = "black",
                         segment.size = 0.25,
                         na.rm = TRUE))
}


# This is used by volcano_plot_with_highlighted_genes to create the
# volcano plot.
ggplot_call_for_volcano_plot <- function (dat, y.label, topic.label) {
  ggplot(dat,aes_string(x = "beta",y = "y",fill = "mean",label = "label")) +
    geom_point(color = "white",stroke = 0.3,shape = 21,na.rm = TRUE) +
    scale_y_continuous(trans = "sqrt",
      breaks = c(0,1,2,5,10,20,50,100,200,500,1e3,2e3,5e3,1e4,2e4,5e4)) +
    scale_fill_gradient2(low = "deepskyblue",mid = "gold",high = "orangered",
                         midpoint = mean(range(dat$mean))) +
    geom_text_repel(color = "gray",size = 5,fontface = "italic",
                    segment.color = "gray",segment.size = 0.25,na.rm = TRUE) +
    labs(x = "log-fold change (\u03b2)",y = y.label,fill = "log10 mean") +
    theme_cowplot(font_size = 18) +
    theme(plot.title = element_text(size = 18,face = "plain"))}



```

```{r DE plots}
MSC_markers <- c("THY1", "NT5E", "ENG")
Chondrocyte_markers <- c("COL2A1", "ACAN", "COL11A1", "SOX9", "SOX5", "SOX6", "COL9A1")
Hepatocyte_markers <- c("AFP", "ALB")
iPSC_markers <- c("POU5F1", "SOX2", "NANOG")

#plots
p1 <- volcano_plot_with_highlighted_genes(diff_count_res = diff_count_topics,
                                          k = "k1",
                                          genes = NA,
                                          label_above_quantile = 0.9995) +
     #ylim(c(0,5000)) +
     guides(fill = "none") +
     ggtitle("topic 1 (Hepatocytes)")
p2 <- volcano_plot_with_highlighted_genes(diff_count_topics,
                                          "k2",
                                          NA,
                                          label_above_quantile = 0.9995) +
     #ylim(c(0,225)) +
     guides(fill = "none") +
     ggtitle("topic 2 (iPSCs)")
p3 <- volcano_plot_with_highlighted_genes(diff_count_topics,
                                          "k4",
                                          NA,
                                          label_above_quantile = 0.9995) +
     #ylim(c(0,225)) +
     guides(fill = "none") +
     ggtitle("topic 4 (iPSC-MSCs)")
p4 <- volcano_plot_with_highlighted_genes(diff_count_topics,
                                          "k6",
                                          NA,
                                          label_above_quantile = 0.9995) +
     #ylim(c(0,225)) +
     guides(fill = "none") +
     ggtitle("topic 6 (iPSC-Chondrocytes)")
p5 <- volcano_plot_with_highlighted_genes(diff_count_topics,
                                          "k7",
                                          NA,
                                          label_above_quantile = 0.9995) +
     #ylim(c(0,225)) +
     guides(fill = "none") +
     ggtitle("topic 7 (Chondrocyte 1)")
p6 <- volcano_plot_with_highlighted_genes(diff_count_topics,
                                          "k3",
                                          NA,
                                          label_above_quantile = 0.9995) +
     #ylim(c(0,225)) +
     guides(fill = "none") +
     ggtitle("topic 3 (Chondrocyte 2)")
p7 <- volcano_plot_with_highlighted_genes(diff_count_topics,
                                          "k5",
                                          NA,
                                          label_above_quantile = 0.9995) +
     #ylim(c(0,225)) +
     guides(fill = "none") +
     ggtitle("topic 5 (Chondrocyte 3)")
p8 <- volcano_plot_with_highlighted_genes(diff_count_chondro,
                                          "k7+k6+k5+k3",
                                          NA,
                                          label_above_quantile = 0.9995) +
     #ylim(c(0,225)) +
     guides(fill = "none") +
     ggtitle("topics 7,6,5,3 (Chondrocyte)")
plot_grid(p1,p2,p3,p4,p5,p6,p7,nrow = 3,ncol = 3)

```

